name: ☂ Code Coverage

on:
  push:
    branches: [ main ]

  pull_request:
    branches: [ '**' ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  coverage:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: ⚙️ Install libsystemd-dev
        run: |
          sudo apt-get update -qqy
          sudo apt-get -y install libsystemd-dev
          pkg-config --libs --cflags libsystemd

      - name: Install Stable Cargo Toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          components: cargo
          toolchain: 'stable'

      - name: Install Rust Toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          components: rustc, rust-std, cargo, llvm-tools, llvm-tools-preview
          toolchain: 'nightly'

      - name: Install cargo-llvm-cov
        uses: taiki-e/install-action@cargo-llvm-cov

      - name: Cache Project
        uses: Swatinem/rust-cache@v2

      - name: Generate code coverage
        run: cargo llvm-cov --all-features --workspace --lcov --output-path lcov.info

      - name: Install covfix
        uses: taiki-e/cache-cargo-install-action@v2
        with:
          tool: rust-covfix

      - name: Run covfix
        run: rust-covfix lcov.info -o lcov.info --verbose

      - name: Upload to codecov.io
        uses: codecov/codecov-action@v5
        continue-on-error: true
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: jeckhart/bottle-time-processor
          fail_ci_if_error: false
          files: lcov.info
